<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="73" passed="73" failed="0" skipped="0">
  <reporter-output>
  </reporter-output>
<<<<<<< Updated upstream
  <suite started-at="2022-01-20T09:47:48 CST" name="Tests" finished-at="2022-01-20T09:48:41 CST" duration-ms="52272">
    <groups>
    </groups>
    <test started-at="2022-01-20T09:47:48 CST" name="DAO" finished-at="2022-01-20T09:48:25 CST" duration-ms="36939">
      <class name="com.shield.tests.dao.UserDAOTests">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.shield.tests.dao.UserDAOTests@71e5f61d]" started-at="2022-01-20T09:48:13 CST" name="setup" finished-at="2022-01-20T09:48:14 CST" duration-ms="952" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="checkUserByUsername()[pri:0, instance:com.shield.tests.dao.UserDAOTests@71e5f61d]" started-at="2022-01-20T09:48:14 CST" name="checkUserByUsername" finished-at="2022-01-20T09:48:15 CST" duration-ms="1019" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkUserByUsername -->
        <test-method signature="checkUsernameAndPassword()[pri:0, instance:com.shield.tests.dao.UserDAOTests@71e5f61d]" started-at="2022-01-20T09:48:15 CST" name="checkUsernameAndPassword" finished-at="2022-01-20T09:48:16 CST" duration-ms="978" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkUsernameAndPassword -->
        <test-method signature="createUser()[pri:0, instance:com.shield.tests.dao.UserDAOTests@71e5f61d]" started-at="2022-01-20T09:48:16 CST" name="createUser" finished-at="2022-01-20T09:48:17 CST" duration-ms="962" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createUser -->
        <test-method signature="getAllUsers()[pri:0, instance:com.shield.tests.dao.UserDAOTests@71e5f61d]" started-at="2022-01-20T09:48:17 CST" name="getAllUsers" finished-at="2022-01-20T09:48:18 CST" duration-ms="499" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getAllUsers -->
        <test-method signature="getUserClaimsByUser()[pri:0, instance:com.shield.tests.dao.UserDAOTests@71e5f61d]" started-at="2022-01-20T09:48:18 CST" name="getUserClaimsByUser" finished-at="2022-01-20T09:48:18 CST" duration-ms="474" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getUserClaimsByUser -->
        <test-method signature="selectUserById()[pri:0, instance:com.shield.tests.dao.UserDAOTests@71e5f61d]" started-at="2022-01-20T09:48:18 CST" name="selectUserById" finished-at="2022-01-20T09:48:19 CST" duration-ms="475" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- selectUserById -->
        <test-method signature="selectUserByIdFail()[pri:0, instance:com.shield.tests.dao.UserDAOTests@71e5f61d]" started-at="2022-01-20T09:48:19 CST" name="selectUserByIdFail" finished-at="2022-01-20T09:48:19 CST" duration-ms="486" status="PASS">
=======
  <suite started-at="2022-01-20T16:19:11 CST" name="Tests" finished-at="2022-01-20T16:20:05 CST" duration-ms="53722">
    <groups>
    </groups>
    <test started-at="2022-01-20T16:19:11 CST" name="DAO" finished-at="2022-01-20T16:19:49 CST" duration-ms="37689">
      <class name="com.shield.tests.dao.UserDAOTests">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.shield.tests.dao.UserDAOTests@71e5f61d]" started-at="2022-01-20T16:19:37 CST" name="setup" finished-at="2022-01-20T16:19:38 CST" duration-ms="994" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="checkUserByUsername()[pri:0, instance:com.shield.tests.dao.UserDAOTests@71e5f61d]" started-at="2022-01-20T16:19:38 CST" name="checkUserByUsername" finished-at="2022-01-20T16:19:39 CST" duration-ms="1003" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkUserByUsername -->
        <test-method signature="checkUsernameAndPassword()[pri:0, instance:com.shield.tests.dao.UserDAOTests@71e5f61d]" started-at="2022-01-20T16:19:39 CST" name="checkUsernameAndPassword" finished-at="2022-01-20T16:19:40 CST" duration-ms="1004" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkUsernameAndPassword -->
        <test-method signature="createUser()[pri:0, instance:com.shield.tests.dao.UserDAOTests@71e5f61d]" started-at="2022-01-20T16:19:40 CST" name="createUser" finished-at="2022-01-20T16:19:41 CST" duration-ms="967" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createUser -->
        <test-method signature="getAllUsers()[pri:0, instance:com.shield.tests.dao.UserDAOTests@71e5f61d]" started-at="2022-01-20T16:19:41 CST" name="getAllUsers" finished-at="2022-01-20T16:19:41 CST" duration-ms="486" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getAllUsers -->
        <test-method signature="getUserClaimsByUser()[pri:0, instance:com.shield.tests.dao.UserDAOTests@71e5f61d]" started-at="2022-01-20T16:19:41 CST" name="getUserClaimsByUser" finished-at="2022-01-20T16:19:42 CST" duration-ms="481" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getUserClaimsByUser -->
        <test-method signature="selectUserById()[pri:0, instance:com.shield.tests.dao.UserDAOTests@71e5f61d]" started-at="2022-01-20T16:19:42 CST" name="selectUserById" finished-at="2022-01-20T16:19:42 CST" duration-ms="509" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- selectUserById -->
        <test-method signature="selectUserByIdFail()[pri:0, instance:com.shield.tests.dao.UserDAOTests@71e5f61d]" started-at="2022-01-20T16:19:42 CST" name="selectUserByIdFail" finished-at="2022-01-20T16:19:43 CST" duration-ms="481" status="PASS">
>>>>>>> Stashed changes
          <exception class="com.shield.customexceptions.UserNotFound">
            <message>
              <![CDATA[User not found]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.shield.customexceptions.UserNotFound: User not found
at com.shield.daos.user.UserDAOImp.getUserById(UserDAOImp.java:51)
at com.shield.tests.dao.UserDAOTests.selectUserByIdFail(UserDAOTests.java:43)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.shield.customexceptions.UserNotFound -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- selectUserByIdFail -->
<<<<<<< Updated upstream
        <test-method signature="insertUserImage()[pri:1, instance:com.shield.tests.dao.UserDAOTests@71e5f61d]" started-at="2022-01-20T09:48:19 CST" name="insertUserImage" finished-at="2022-01-20T09:48:20 CST" duration-ms="995" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- insertUserImage -->
        <test-method signature="getUserImage()[pri:2, instance:com.shield.tests.dao.UserDAOTests@71e5f61d]" started-at="2022-01-20T09:48:20 CST" name="getUserImage" finished-at="2022-01-20T09:48:22 CST" duration-ms="2418" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getUserImage -->
        <test-method signature="checkUserImage()[pri:3, instance:com.shield.tests.dao.UserDAOTests@71e5f61d]" started-at="2022-01-20T09:48:22 CST" name="checkUserImage" finished-at="2022-01-20T09:48:25 CST" duration-ms="2410" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkUserImage -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.shield.tests.dao.UserDAOTests@71e5f61d]" started-at="2022-01-20T09:48:25 CST" name="tearDown" finished-at="2022-01-20T09:48:25 CST" duration-ms="484" status="PASS">
=======
        <test-method signature="insertUserImage()[pri:1, instance:com.shield.tests.dao.UserDAOTests@71e5f61d]" started-at="2022-01-20T16:19:43 CST" name="insertUserImage" finished-at="2022-01-20T16:19:44 CST" duration-ms="969" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- insertUserImage -->
        <test-method signature="getUserImage()[pri:2, instance:com.shield.tests.dao.UserDAOTests@71e5f61d]" started-at="2022-01-20T16:19:44 CST" name="getUserImage" finished-at="2022-01-20T16:19:46 CST" duration-ms="2497" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getUserImage -->
        <test-method signature="checkUserImage()[pri:3, instance:com.shield.tests.dao.UserDAOTests@71e5f61d]" started-at="2022-01-20T16:19:46 CST" name="checkUserImage" finished-at="2022-01-20T16:19:49 CST" duration-ms="2437" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkUserImage -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.shield.tests.dao.UserDAOTests@71e5f61d]" started-at="2022-01-20T16:19:49 CST" name="tearDown" finished-at="2022-01-20T16:19:49 CST" duration-ms="503" status="PASS">
>>>>>>> Stashed changes
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.shield.tests.dao.UserDAOTests -->
      <class name="com.shield.tests.dao.DebriefDAOTests">
<<<<<<< Updated upstream
        <test-method is-config="true" signature="setup()[pri:0, instance:com.shield.tests.dao.DebriefDAOTests@5ac86ba5]" started-at="2022-01-20T09:47:55 CST" name="setup" finished-at="2022-01-20T09:47:56 CST" duration-ms="988" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="createDebrief()[pri:0, instance:com.shield.tests.dao.DebriefDAOTests@5ac86ba5]" started-at="2022-01-20T09:47:56 CST" name="createDebrief" finished-at="2022-01-20T09:47:57 CST" duration-ms="968" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createDebrief -->
        <test-method signature="getDebrief()[pri:0, instance:com.shield.tests.dao.DebriefDAOTests@5ac86ba5]" started-at="2022-01-20T09:47:57 CST" name="getDebrief" finished-at="2022-01-20T09:47:58 CST" duration-ms="963" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getDebrief -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.shield.tests.dao.DebriefDAOTests@5ac86ba5]" started-at="2022-01-20T09:47:58 CST" name="teardown" finished-at="2022-01-20T09:47:58 CST" duration-ms="516" status="PASS">
=======
        <test-method is-config="true" signature="setup()[pri:0, instance:com.shield.tests.dao.DebriefDAOTests@5ac86ba5]" started-at="2022-01-20T16:19:18 CST" name="setup" finished-at="2022-01-20T16:19:19 CST" duration-ms="1017" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="createDebrief()[pri:0, instance:com.shield.tests.dao.DebriefDAOTests@5ac86ba5]" started-at="2022-01-20T16:19:19 CST" name="createDebrief" finished-at="2022-01-20T16:19:20 CST" duration-ms="1050" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createDebrief -->
        <test-method signature="getDebrief()[pri:0, instance:com.shield.tests.dao.DebriefDAOTests@5ac86ba5]" started-at="2022-01-20T16:19:20 CST" name="getDebrief" finished-at="2022-01-20T16:19:21 CST" duration-ms="975" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getDebrief -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.shield.tests.dao.DebriefDAOTests@5ac86ba5]" started-at="2022-01-20T16:19:21 CST" name="teardown" finished-at="2022-01-20T16:19:21 CST" duration-ms="500" status="PASS">
>>>>>>> Stashed changes
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.shield.tests.dao.DebriefDAOTests -->
      <class name="com.shield.tests.dao.ClaimDAOTests">
<<<<<<< Updated upstream
        <test-method is-config="true" signature="setup()[pri:0, instance:com.shield.tests.dao.ClaimDAOTests@4215838f]" started-at="2022-01-20T09:47:48 CST" name="setup" finished-at="2022-01-20T09:47:49 CST" duration-ms="1030" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="selectClaimById()[pri:0, instance:com.shield.tests.dao.ClaimDAOTests@4215838f]" started-at="2022-01-20T09:47:49 CST" name="selectClaimById" finished-at="2022-01-20T09:47:50 CST" duration-ms="989" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- selectClaimById -->
        <test-method signature="createClaimById()[pri:1, instance:com.shield.tests.dao.ClaimDAOTests@4215838f]" started-at="2022-01-20T09:47:50 CST" name="createClaimById" finished-at="2022-01-20T09:47:51 CST" duration-ms="980" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createClaimById -->
        <test-method signature="ApproveClaimById()[pri:2, instance:com.shield.tests.dao.ClaimDAOTests@4215838f]" started-at="2022-01-20T09:47:51 CST" name="ApproveClaimById" finished-at="2022-01-20T09:47:53 CST" duration-ms="1447" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ApproveClaimById -->
        <test-method signature="DenyClaimById()[pri:3, instance:com.shield.tests.dao.ClaimDAOTests@4215838f]" started-at="2022-01-20T09:47:53 CST" name="DenyClaimById" finished-at="2022-01-20T09:47:54 CST" duration-ms="1466" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DenyClaimById -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.shield.tests.dao.ClaimDAOTests@4215838f]" started-at="2022-01-20T09:47:54 CST" name="tearDown" finished-at="2022-01-20T09:47:55 CST" duration-ms="482" status="PASS">
=======
        <test-method is-config="true" signature="setup()[pri:0, instance:com.shield.tests.dao.ClaimDAOTests@4215838f]" started-at="2022-01-20T16:19:11 CST" name="setup" finished-at="2022-01-20T16:19:12 CST" duration-ms="979" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="selectClaimById()[pri:0, instance:com.shield.tests.dao.ClaimDAOTests@4215838f]" started-at="2022-01-20T16:19:12 CST" name="selectClaimById" finished-at="2022-01-20T16:19:13 CST" duration-ms="1005" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- selectClaimById -->
        <test-method signature="createClaimById()[pri:1, instance:com.shield.tests.dao.ClaimDAOTests@4215838f]" started-at="2022-01-20T16:19:13 CST" name="createClaimById" finished-at="2022-01-20T16:19:14 CST" duration-ms="983" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createClaimById -->
        <test-method signature="ApproveClaimById()[pri:2, instance:com.shield.tests.dao.ClaimDAOTests@4215838f]" started-at="2022-01-20T16:19:14 CST" name="ApproveClaimById" finished-at="2022-01-20T16:19:16 CST" duration-ms="1533" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ApproveClaimById -->
        <test-method signature="DenyClaimById()[pri:3, instance:com.shield.tests.dao.ClaimDAOTests@4215838f]" started-at="2022-01-20T16:19:16 CST" name="DenyClaimById" finished-at="2022-01-20T16:19:17 CST" duration-ms="1446" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DenyClaimById -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.shield.tests.dao.ClaimDAOTests@4215838f]" started-at="2022-01-20T16:19:17 CST" name="tearDown" finished-at="2022-01-20T16:19:18 CST" duration-ms="494" status="PASS">
>>>>>>> Stashed changes
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.shield.tests.dao.ClaimDAOTests -->
      <class name="com.shield.tests.dao.EmployeeDAOTests">
<<<<<<< Updated upstream
        <test-method is-config="true" signature="setup()[pri:0, instance:com.shield.tests.dao.EmployeeDAOTests@191ae03f]" started-at="2022-01-20T09:47:58 CST" name="setup" finished-at="2022-01-20T09:48:00 CST" duration-ms="1336" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="checkEmployeeImage()[pri:0, instance:com.shield.tests.dao.EmployeeDAOTests@191ae03f]" started-at="2022-01-20T09:48:00 CST" name="checkEmployeeImage" finished-at="2022-01-20T09:48:02 CST" duration-ms="2870" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkEmployeeImage -->
        <test-method signature="getAgentDebriefings()[pri:0, instance:com.shield.tests.dao.EmployeeDAOTests@191ae03f]" started-at="2022-01-20T09:48:02 CST" name="getAgentDebriefings" finished-at="2022-01-20T09:48:03 CST" duration-ms="973" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getAgentDebriefings -->
        <test-method signature="getAllAgentDebriefings()[pri:0, instance:com.shield.tests.dao.EmployeeDAOTests@191ae03f]" started-at="2022-01-20T09:48:03 CST" name="getAllAgentDebriefings" finished-at="2022-01-20T09:48:05 CST" duration-ms="1479" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getAllAgentDebriefings -->
        <test-method signature="getAllClaims()[pri:0, instance:com.shield.tests.dao.EmployeeDAOTests@191ae03f]" started-at="2022-01-20T09:48:05 CST" name="getAllClaims" finished-at="2022-01-20T09:48:06 CST" duration-ms="1450" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getAllClaims -->
        <test-method signature="getEmployeeById()[pri:0, instance:com.shield.tests.dao.EmployeeDAOTests@191ae03f]" started-at="2022-01-20T09:48:06 CST" name="getEmployeeById" finished-at="2022-01-20T09:48:07 CST" duration-ms="481" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getEmployeeById -->
        <test-method signature="getEmployeeImage()[pri:0, instance:com.shield.tests.dao.EmployeeDAOTests@191ae03f]" started-at="2022-01-20T09:48:07 CST" name="getEmployeeImage" finished-at="2022-01-20T09:48:09 CST" duration-ms="2465" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getEmployeeImage -->
        <test-method signature="getLeaderboard()[pri:0, instance:com.shield.tests.dao.EmployeeDAOTests@191ae03f]" started-at="2022-01-20T09:48:09 CST" name="getLeaderboard" finished-at="2022-01-20T09:48:10 CST" duration-ms="485" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLeaderboard -->
        <test-method signature="getUserClaimsByAgent()[pri:0, instance:com.shield.tests.dao.EmployeeDAOTests@191ae03f]" started-at="2022-01-20T09:48:10 CST" name="getUserClaimsByAgent" finished-at="2022-01-20T09:48:11 CST" duration-ms="982" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getUserClaimsByAgent -->
        <test-method signature="insertEmployeeImage()[pri:0, instance:com.shield.tests.dao.EmployeeDAOTests@191ae03f]" started-at="2022-01-20T09:48:11 CST" name="insertEmployeeImage" finished-at="2022-01-20T09:48:12 CST" duration-ms="943" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- insertEmployeeImage -->
        <test-method signature="loginEmployee()[pri:0, instance:com.shield.tests.dao.EmployeeDAOTests@191ae03f]" started-at="2022-01-20T09:48:12 CST" name="loginEmployee" finished-at="2022-01-20T09:48:13 CST" duration-ms="949" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginEmployee -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.shield.tests.dao.EmployeeDAOTests@191ae03f]" started-at="2022-01-20T09:48:13 CST" name="teardown" finished-at="2022-01-20T09:48:13 CST" duration-ms="495" status="PASS">
=======
        <test-method is-config="true" signature="setup()[pri:0, instance:com.shield.tests.dao.EmployeeDAOTests@191ae03f]" started-at="2022-01-20T16:19:21 CST" name="setup" finished-at="2022-01-20T16:19:22 CST" duration-ms="1002" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="checkEmployeeImage()[pri:0, instance:com.shield.tests.dao.EmployeeDAOTests@191ae03f]" started-at="2022-01-20T16:19:22 CST" name="checkEmployeeImage" finished-at="2022-01-20T16:19:25 CST" duration-ms="2468" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkEmployeeImage -->
        <test-method signature="getAgentDebriefings()[pri:0, instance:com.shield.tests.dao.EmployeeDAOTests@191ae03f]" started-at="2022-01-20T16:19:25 CST" name="getAgentDebriefings" finished-at="2022-01-20T16:19:26 CST" duration-ms="966" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getAgentDebriefings -->
        <test-method signature="getAllAgentDebriefings()[pri:0, instance:com.shield.tests.dao.EmployeeDAOTests@191ae03f]" started-at="2022-01-20T16:19:26 CST" name="getAllAgentDebriefings" finished-at="2022-01-20T16:19:28 CST" duration-ms="2481" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getAllAgentDebriefings -->
        <test-method signature="getAllClaims()[pri:0, instance:com.shield.tests.dao.EmployeeDAOTests@191ae03f]" started-at="2022-01-20T16:19:28 CST" name="getAllClaims" finished-at="2022-01-20T16:19:30 CST" duration-ms="1518" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getAllClaims -->
        <test-method signature="getEmployeeById()[pri:0, instance:com.shield.tests.dao.EmployeeDAOTests@191ae03f]" started-at="2022-01-20T16:19:30 CST" name="getEmployeeById" finished-at="2022-01-20T16:19:30 CST" duration-ms="472" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getEmployeeById -->
        <test-method signature="getEmployeeImage()[pri:0, instance:com.shield.tests.dao.EmployeeDAOTests@191ae03f]" started-at="2022-01-20T16:19:30 CST" name="getEmployeeImage" finished-at="2022-01-20T16:19:33 CST" duration-ms="2441" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getEmployeeImage -->
        <test-method signature="getLeaderboard()[pri:0, instance:com.shield.tests.dao.EmployeeDAOTests@191ae03f]" started-at="2022-01-20T16:19:33 CST" name="getLeaderboard" finished-at="2022-01-20T16:19:33 CST" duration-ms="486" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLeaderboard -->
        <test-method signature="getUserClaimsByAgent()[pri:0, instance:com.shield.tests.dao.EmployeeDAOTests@191ae03f]" started-at="2022-01-20T16:19:33 CST" name="getUserClaimsByAgent" finished-at="2022-01-20T16:19:34 CST" duration-ms="958" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getUserClaimsByAgent -->
        <test-method signature="insertEmployeeImage()[pri:0, instance:com.shield.tests.dao.EmployeeDAOTests@191ae03f]" started-at="2022-01-20T16:19:34 CST" name="insertEmployeeImage" finished-at="2022-01-20T16:19:35 CST" duration-ms="1070" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- insertEmployeeImage -->
        <test-method signature="loginEmployee()[pri:0, instance:com.shield.tests.dao.EmployeeDAOTests@191ae03f]" started-at="2022-01-20T16:19:35 CST" name="loginEmployee" finished-at="2022-01-20T16:19:36 CST" duration-ms="962" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginEmployee -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.shield.tests.dao.EmployeeDAOTests@191ae03f]" started-at="2022-01-20T16:19:36 CST" name="teardown" finished-at="2022-01-20T16:19:37 CST" duration-ms="509" status="PASS">
>>>>>>> Stashed changes
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.shield.tests.dao.EmployeeDAOTests -->
    </test> <!-- DAO -->
<<<<<<< Updated upstream
    <test started-at="2022-01-20T09:48:25 CST" name="Service" finished-at="2022-01-20T09:48:41 CST" duration-ms="15314">
      <class name="com.shield.tests.service.UserServiceTests">
        <test-method signature="badIdForGetUserClaimsByUserService()[pri:0, instance:com.shield.tests.service.UserServiceTests@2f94c4db]" started-at="2022-01-20T09:48:36 CST" name="badIdForGetUserClaimsByUserService" finished-at="2022-01-20T09:48:37 CST" duration-ms="532" status="PASS">
=======
    <test started-at="2022-01-20T16:19:49 CST" name="Service" finished-at="2022-01-20T16:20:05 CST" duration-ms="16015">
      <class name="com.shield.tests.service.UserServiceTests">
        <test-method signature="badIdForGetUserClaimsByUserService()[pri:0, instance:com.shield.tests.service.UserServiceTests@2f94c4db]" started-at="2022-01-20T16:20:01 CST" name="badIdForGetUserClaimsByUserService" finished-at="2022-01-20T16:20:01 CST" duration-ms="524" status="PASS">
>>>>>>> Stashed changes
          <exception class="com.shield.customexceptions.UserNotFound">
            <message>
              <![CDATA[User not found]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.shield.customexceptions.UserNotFound: User not found
at com.shield.daos.user.UserDAOImp.getUserById(UserDAOImp.java:51)
at com.shield.services.user.UserServicesImp.getUserClaimsByUserService(UserServicesImp.java:86)
at com.shield.tests.service.UserServiceTests.badIdForGetUserClaimsByUserService(UserServiceTests.java:49)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.shield.customexceptions.UserNotFound -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- badIdForGetUserClaimsByUserService -->
<<<<<<< Updated upstream
        <test-method signature="badIdGetUserImageService()[pri:0, instance:com.shield.tests.service.UserServiceTests@2f94c4db]" started-at="2022-01-20T09:48:37 CST" name="badIdGetUserImageService" finished-at="2022-01-20T09:48:37 CST" duration-ms="468" status="PASS">
=======
        <test-method signature="badIdGetUserImageService()[pri:0, instance:com.shield.tests.service.UserServiceTests@2f94c4db]" started-at="2022-01-20T16:20:01 CST" name="badIdGetUserImageService" finished-at="2022-01-20T16:20:02 CST" duration-ms="474" status="PASS">
>>>>>>> Stashed changes
          <exception class="com.shield.customexceptions.UserNotFound">
            <message>
              <![CDATA[User not found]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.shield.customexceptions.UserNotFound: User not found
at com.shield.daos.user.UserDAOImp.getUserById(UserDAOImp.java:51)
at com.shield.services.user.UserServicesImp.getUserImageService(UserServicesImp.java:104)
at com.shield.tests.service.UserServiceTests.badIdGetUserImageService(UserServiceTests.java:60)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.shield.customexceptions.UserNotFound -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- badIdGetUserImageService -->
<<<<<<< Updated upstream
        <test-method signature="badIdInsertUserImageService()[pri:0, instance:com.shield.tests.service.UserServiceTests@2f94c4db]" started-at="2022-01-20T09:48:37 CST" name="badIdInsertUserImageService" finished-at="2022-01-20T09:48:38 CST" duration-ms="480" status="PASS">
=======
        <test-method signature="badIdInsertUserImageService()[pri:0, instance:com.shield.tests.service.UserServiceTests@2f94c4db]" started-at="2022-01-20T16:20:02 CST" name="badIdInsertUserImageService" finished-at="2022-01-20T16:20:02 CST" duration-ms="485" status="PASS">
>>>>>>> Stashed changes
          <exception class="com.shield.customexceptions.UserNotFound">
            <message>
              <![CDATA[User not found]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.shield.customexceptions.UserNotFound: User not found
at com.shield.daos.user.UserDAOImp.getUserById(UserDAOImp.java:51)
at com.shield.services.user.UserServicesImp.insertUserImageService(UserServicesImp.java:97)
at com.shield.tests.service.UserServiceTests.badIdInsertUserImageService(UserServiceTests.java:55)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.shield.customexceptions.UserNotFound -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- badIdInsertUserImageService -->
<<<<<<< Updated upstream
        <test-method signature="badPasswordForCheckingLogin()[pri:0, instance:com.shield.tests.service.UserServiceTests@2f94c4db]" started-at="2022-01-20T09:48:38 CST" name="badPasswordForCheckingLogin" finished-at="2022-01-20T09:48:38 CST" duration-ms="466" status="PASS">
=======
        <test-method signature="badPasswordForCheckingLogin()[pri:0, instance:com.shield.tests.service.UserServiceTests@2f94c4db]" started-at="2022-01-20T16:20:02 CST" name="badPasswordForCheckingLogin" finished-at="2022-01-20T16:20:03 CST" duration-ms="482" status="PASS">
>>>>>>> Stashed changes
          <exception class="com.shield.customexceptions.InvalidPassword">
            <message>
              <![CDATA[Invalid password]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.shield.customexceptions.InvalidPassword: Invalid password
at com.shield.services.user.UserServicesImp.checkUserLoginService(UserServicesImp.java:76)
at com.shield.tests.service.UserServiceTests.badPasswordForCheckingLogin(UserServiceTests.java:44)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.shield.customexceptions.InvalidPassword -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- badPasswordForCheckingLogin -->
<<<<<<< Updated upstream
        <test-method signature="badUserIdForGettingUser()[pri:0, instance:com.shield.tests.service.UserServiceTests@2f94c4db]" started-at="2022-01-20T09:48:38 CST" name="badUserIdForGettingUser" finished-at="2022-01-20T09:48:39 CST" duration-ms="485" status="PASS">
=======
        <test-method signature="badUserIdForGettingUser()[pri:0, instance:com.shield.tests.service.UserServiceTests@2f94c4db]" started-at="2022-01-20T16:20:03 CST" name="badUserIdForGettingUser" finished-at="2022-01-20T16:20:03 CST" duration-ms="497" status="PASS">
>>>>>>> Stashed changes
          <exception class="com.shield.customexceptions.UserNotFound">
            <message>
              <![CDATA[User not found]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.shield.customexceptions.UserNotFound: User not found
at com.shield.services.user.UserServicesImp.getUserByIdService(UserServicesImp.java:36)
at com.shield.tests.service.UserServiceTests.badUserIdForGettingUser(UserServiceTests.java:32)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.shield.customexceptions.UserNotFound -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- badUserIdForGettingUser -->
<<<<<<< Updated upstream
        <test-method signature="badUsernameForCheckingLogin()[pri:0, instance:com.shield.tests.service.UserServiceTests@2f94c4db]" started-at="2022-01-20T09:48:39 CST" name="badUsernameForCheckingLogin" finished-at="2022-01-20T09:48:39 CST" duration-ms="479" status="PASS">
=======
        <test-method signature="badUsernameForCheckingLogin()[pri:0, instance:com.shield.tests.service.UserServiceTests@2f94c4db]" started-at="2022-01-20T16:20:03 CST" name="badUsernameForCheckingLogin" finished-at="2022-01-20T16:20:04 CST" duration-ms="473" status="PASS">
>>>>>>> Stashed changes
          <exception class="com.shield.customexceptions.InvalidUsername">
            <message>
              <![CDATA[Invalid username]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.shield.customexceptions.InvalidUsername: Invalid username
at com.shield.services.user.UserServicesImp.checkUserLoginService(UserServicesImp.java:78)
at com.shield.tests.service.UserServiceTests.badUsernameForCheckingLogin(UserServiceTests.java:38)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.shield.customexceptions.InvalidUsername -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- badUsernameForCheckingLogin -->
<<<<<<< Updated upstream
        <test-method signature="duplicateEmployeeUsernameForCreateUserService()[pri:0, instance:com.shield.tests.service.UserServiceTests@2f94c4db]" started-at="2022-01-20T09:48:39 CST" name="duplicateEmployeeUsernameForCreateUserService" finished-at="2022-01-20T09:48:40 CST" duration-ms="956" status="PASS">
=======
        <test-method signature="duplicateEmployeeUsernameForCreateUserService()[pri:0, instance:com.shield.tests.service.UserServiceTests@2f94c4db]" started-at="2022-01-20T16:20:04 CST" name="duplicateEmployeeUsernameForCreateUserService" finished-at="2022-01-20T16:20:05 CST" duration-ms="975" status="PASS">
>>>>>>> Stashed changes
          <exception class="com.shield.customexceptions.UsernameAlreadyExists">
            <message>
              <![CDATA[Username is already taken]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.shield.customexceptions.UsernameAlreadyExists: Username is already taken
at com.shield.services.user.UserServicesImp.createUser(UserServicesImp.java:47)
at com.shield.tests.service.UserServiceTests.duplicateEmployeeUsernameForCreateUserService(UserServiceTests.java:69)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.shield.customexceptions.UsernameAlreadyExists -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- duplicateEmployeeUsernameForCreateUserService -->
<<<<<<< Updated upstream
        <test-method signature="duplicateUserUsernameForCreateUserService()[pri:0, instance:com.shield.tests.service.UserServiceTests@2f94c4db]" started-at="2022-01-20T09:48:40 CST" name="duplicateUserUsernameForCreateUserService" finished-at="2022-01-20T09:48:41 CST" duration-ms="498" status="PASS">
=======
        <test-method signature="duplicateUserUsernameForCreateUserService()[pri:0, instance:com.shield.tests.service.UserServiceTests@2f94c4db]" started-at="2022-01-20T16:20:05 CST" name="duplicateUserUsernameForCreateUserService" finished-at="2022-01-20T16:20:05 CST" duration-ms="490" status="PASS">
>>>>>>> Stashed changes
          <exception class="com.shield.customexceptions.UsernameAlreadyExists">
            <message>
              <![CDATA[Username is already taken]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.shield.customexceptions.UsernameAlreadyExists: Username is already taken
at com.shield.services.user.UserServicesImp.createUser(UserServicesImp.java:47)
at com.shield.tests.service.UserServiceTests.duplicateUserUsernameForCreateUserService(UserServiceTests.java:65)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.shield.customexceptions.UsernameAlreadyExists -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- duplicateUserUsernameForCreateUserService -->
      </class> <!-- com.shield.tests.service.UserServiceTests -->
      <class name="com.shield.tests.service.DebriefServiceTests">
<<<<<<< Updated upstream
        <test-method signature="badIdForcreateDebriefService()[pri:0, instance:com.shield.tests.service.DebriefServiceTests@3a4e343]" started-at="2022-01-20T09:48:31 CST" name="badIdForcreateDebriefService" finished-at="2022-01-20T09:48:31 CST" duration-ms="471" status="PASS">
=======
        <test-method signature="badIdForcreateDebriefService()[pri:0, instance:com.shield.tests.service.DebriefServiceTests@3a4e343]" started-at="2022-01-20T16:19:55 CST" name="badIdForcreateDebriefService" finished-at="2022-01-20T16:19:55 CST" duration-ms="473" status="PASS">
>>>>>>> Stashed changes
          <exception class="com.shield.customexceptions.EmployeeNotFound">
            <message>
              <![CDATA[The employee was not found.]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.shield.customexceptions.EmployeeNotFound: The employee was not found.
at com.shield.daos.employee.EmployeeDAOImp.getEmployeeById(EmployeeDAOImp.java:69)
at com.shield.services.debrief.DebriefServiceImp.createDebriefService(DebriefServiceImp.java:27)
at com.shield.tests.service.DebriefServiceTests.badIdForcreateDebriefService(DebriefServiceTests.java:22)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.shield.customexceptions.EmployeeNotFound -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- badIdForcreateDebriefService -->
      </class> <!-- com.shield.tests.service.DebriefServiceTests -->
      <class name="com.shield.tests.service.EmployeeServiceMockitoTests">
<<<<<<< Updated upstream
        <test-method is-config="true" signature="setup()[pri:0, instance:com.shield.tests.service.EmployeeServiceMockitoTests@6a1d204a]" started-at="2022-01-20T09:48:31 CST" name="setup" finished-at="2022-01-20T09:48:31 CST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="MockGetAgentDebriefingsService()[pri:0, instance:com.shield.tests.service.EmployeeServiceMockitoTests@6a1d204a]" started-at="2022-01-20T09:48:31 CST" name="MockGetAgentDebriefingsService" finished-at="2022-01-20T09:48:31 CST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- MockGetAgentDebriefingsService -->
        <test-method signature="mockGetAllAgentDebriefingsService()[pri:0, instance:com.shield.tests.service.EmployeeServiceMockitoTests@6a1d204a]" started-at="2022-01-20T09:48:31 CST" name="mockGetAllAgentDebriefingsService" finished-at="2022-01-20T09:48:31 CST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- mockGetAllAgentDebriefingsService -->
        <test-method signature="mockGetEmployeeImageService()[pri:0, instance:com.shield.tests.service.EmployeeServiceMockitoTests@6a1d204a]" started-at="2022-01-20T09:48:31 CST" name="mockGetEmployeeImageService" finished-at="2022-01-20T09:48:31 CST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- mockGetEmployeeImageService -->
        <test-method signature="mockGetEmployeeServiceById()[pri:0, instance:com.shield.tests.service.EmployeeServiceMockitoTests@6a1d204a]" started-at="2022-01-20T09:48:31 CST" name="mockGetEmployeeServiceById" finished-at="2022-01-20T09:48:31 CST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- mockGetEmployeeServiceById -->
        <test-method signature="mockGetUserClaimsByAgentService()[pri:0, instance:com.shield.tests.service.EmployeeServiceMockitoTests@6a1d204a]" started-at="2022-01-20T09:48:31 CST" name="mockGetUserClaimsByAgentService" finished-at="2022-01-20T09:48:31 CST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- mockGetUserClaimsByAgentService -->
        <test-method signature="mockInsertEmployeeImageService()[pri:0, instance:com.shield.tests.service.EmployeeServiceMockitoTests@6a1d204a]" started-at="2022-01-20T09:48:31 CST" name="mockInsertEmployeeImageService" finished-at="2022-01-20T09:48:31 CST" duration-ms="1" status="PASS">
=======
        <test-method is-config="true" signature="setup()[pri:0, instance:com.shield.tests.service.EmployeeServiceMockitoTests@6a1d204a]" started-at="2022-01-20T16:19:55 CST" name="setup" finished-at="2022-01-20T16:19:55 CST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="MockGetAgentDebriefingsService()[pri:0, instance:com.shield.tests.service.EmployeeServiceMockitoTests@6a1d204a]" started-at="2022-01-20T16:19:55 CST" name="MockGetAgentDebriefingsService" finished-at="2022-01-20T16:19:55 CST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- MockGetAgentDebriefingsService -->
        <test-method signature="mockGetEmployeeImageService()[pri:0, instance:com.shield.tests.service.EmployeeServiceMockitoTests@6a1d204a]" started-at="2022-01-20T16:19:55 CST" name="mockGetEmployeeImageService" finished-at="2022-01-20T16:19:55 CST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- mockGetEmployeeImageService -->
        <test-method signature="mockGetAllAgentDebriefingsService()[pri:0, instance:com.shield.tests.service.EmployeeServiceMockitoTests@6a1d204a]" started-at="2022-01-20T16:19:55 CST" name="mockGetAllAgentDebriefingsService" finished-at="2022-01-20T16:19:55 CST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- mockGetAllAgentDebriefingsService -->
        <test-method signature="mockGetEmployeeServiceById()[pri:0, instance:com.shield.tests.service.EmployeeServiceMockitoTests@6a1d204a]" started-at="2022-01-20T16:19:55 CST" name="mockGetEmployeeServiceById" finished-at="2022-01-20T16:19:55 CST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- mockGetEmployeeServiceById -->
        <test-method signature="mockGetUserClaimsByAgentService()[pri:0, instance:com.shield.tests.service.EmployeeServiceMockitoTests@6a1d204a]" started-at="2022-01-20T16:19:55 CST" name="mockGetUserClaimsByAgentService" finished-at="2022-01-20T16:19:55 CST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- mockGetUserClaimsByAgentService -->
        <test-method signature="mockInsertEmployeeImageService()[pri:0, instance:com.shield.tests.service.EmployeeServiceMockitoTests@6a1d204a]" started-at="2022-01-20T16:19:55 CST" name="mockInsertEmployeeImageService" finished-at="2022-01-20T16:19:55 CST" duration-ms="1" status="PASS">
>>>>>>> Stashed changes
          <reporter-output>
          </reporter-output>
        </test-method> <!-- mockInsertEmployeeImageService -->
      </class> <!-- com.shield.tests.service.EmployeeServiceMockitoTests -->
      <class name="com.shield.tests.service.ClaimServiceMockitoTest">
<<<<<<< Updated upstream
        <test-method is-config="true" signature="setup()[pri:0, instance:com.shield.tests.service.ClaimServiceMockitoTest@5ab14cb9]" started-at="2022-01-20T09:48:25 CST" name="setup" finished-at="2022-01-20T09:48:26 CST" duration-ms="585" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="approveClaimServiceMock()[pri:0, instance:com.shield.tests.service.ClaimServiceMockitoTest@5ab14cb9]" started-at="2022-01-20T09:48:26 CST" name="approveClaimServiceMock" finished-at="2022-01-20T09:48:26 CST" duration-ms="17" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- approveClaimServiceMock -->
        <test-method signature="createClaimServiceMock()[pri:0, instance:com.shield.tests.service.ClaimServiceMockitoTest@5ab14cb9]" started-at="2022-01-20T09:48:26 CST" name="createClaimServiceMock" finished-at="2022-01-20T09:48:26 CST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createClaimServiceMock -->
        <test-method signature="denyClaimServiceMock()[pri:0, instance:com.shield.tests.service.ClaimServiceMockitoTest@5ab14cb9]" started-at="2022-01-20T09:48:26 CST" name="denyClaimServiceMock" finished-at="2022-01-20T09:48:26 CST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- denyClaimServiceMock -->
        <test-method signature="getClaimServiceByIdMock()[pri:0, instance:com.shield.tests.service.ClaimServiceMockitoTest@5ab14cb9]" started-at="2022-01-20T09:48:26 CST" name="getClaimServiceByIdMock" finished-at="2022-01-20T09:48:26 CST" duration-ms="1" status="PASS">
=======
        <test-method is-config="true" signature="setup()[pri:0, instance:com.shield.tests.service.ClaimServiceMockitoTest@5ab14cb9]" started-at="2022-01-20T16:19:49 CST" name="setup" finished-at="2022-01-20T16:19:50 CST" duration-ms="533" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="approveClaimServiceMock()[pri:0, instance:com.shield.tests.service.ClaimServiceMockitoTest@5ab14cb9]" started-at="2022-01-20T16:19:50 CST" name="approveClaimServiceMock" finished-at="2022-01-20T16:19:50 CST" duration-ms="17" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- approveClaimServiceMock -->
        <test-method signature="createClaimServiceMock()[pri:0, instance:com.shield.tests.service.ClaimServiceMockitoTest@5ab14cb9]" started-at="2022-01-20T16:19:50 CST" name="createClaimServiceMock" finished-at="2022-01-20T16:19:50 CST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createClaimServiceMock -->
        <test-method signature="getClaimServiceByIdMock()[pri:0, instance:com.shield.tests.service.ClaimServiceMockitoTest@5ab14cb9]" started-at="2022-01-20T16:19:50 CST" name="getClaimServiceByIdMock" finished-at="2022-01-20T16:19:50 CST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getClaimServiceByIdMock -->
        <test-method signature="denyClaimServiceMock()[pri:0, instance:com.shield.tests.service.ClaimServiceMockitoTest@5ab14cb9]" started-at="2022-01-20T16:19:50 CST" name="denyClaimServiceMock" finished-at="2022-01-20T16:19:50 CST" duration-ms="0" status="PASS">
>>>>>>> Stashed changes
          <reporter-output>
          </reporter-output>
        </test-method> <!-- denyClaimServiceMock -->
      </class> <!-- com.shield.tests.service.ClaimServiceMockitoTest -->
      <class name="com.shield.tests.service.ClaimServiceTests">
<<<<<<< Updated upstream
        <test-method signature="badClaimIdForApproveClaimService()[pri:0, instance:com.shield.tests.service.ClaimServiceTests@25bcd0c7]" started-at="2022-01-20T09:48:26 CST" name="badClaimIdForApproveClaimService" finished-at="2022-01-20T09:48:27 CST" duration-ms="978" status="PASS">
=======
        <test-method signature="badClaimIdForApproveClaimService()[pri:0, instance:com.shield.tests.service.ClaimServiceTests@25bcd0c7]" started-at="2022-01-20T16:19:50 CST" name="badClaimIdForApproveClaimService" finished-at="2022-01-20T16:19:51 CST" duration-ms="965" status="PASS">
>>>>>>> Stashed changes
          <exception class="com.shield.customexceptions.ClaimNotFound">
            <message>
              <![CDATA[Claim not found]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.shield.customexceptions.ClaimNotFound: Claim not found
at com.shield.services.claim.ClaimServiceImp.approveClaimService(ClaimServiceImp.java:67)
at com.shield.tests.service.ClaimServiceTests.badClaimIdForApproveClaimService(ClaimServiceTests.java:55)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.shield.customexceptions.ClaimNotFound -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- badClaimIdForApproveClaimService -->
<<<<<<< Updated upstream
        <test-method signature="badClaimIdForDenyClaimService()[pri:0, instance:com.shield.tests.service.ClaimServiceTests@25bcd0c7]" started-at="2022-01-20T09:48:27 CST" name="badClaimIdForDenyClaimService" finished-at="2022-01-20T09:48:28 CST" duration-ms="965" status="PASS">
=======
        <test-method signature="badClaimIdForDenyClaimService()[pri:0, instance:com.shield.tests.service.ClaimServiceTests@25bcd0c7]" started-at="2022-01-20T16:19:51 CST" name="badClaimIdForDenyClaimService" finished-at="2022-01-20T16:19:52 CST" duration-ms="975" status="PASS">
>>>>>>> Stashed changes
          <exception class="com.shield.customexceptions.ClaimNotFound">
            <message>
              <![CDATA[Claim not found]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.shield.customexceptions.ClaimNotFound: Claim not found
at com.shield.services.claim.ClaimServiceImp.denyClaimService(ClaimServiceImp.java:82)
at com.shield.tests.service.ClaimServiceTests.badClaimIdForDenyClaimService(ClaimServiceTests.java:76)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.shield.customexceptions.ClaimNotFound -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- badClaimIdForDenyClaimService -->
<<<<<<< Updated upstream
        <test-method signature="badClaimIdForGetClaimService()[pri:0, instance:com.shield.tests.service.ClaimServiceTests@25bcd0c7]" started-at="2022-01-20T09:48:28 CST" name="badClaimIdForGetClaimService" finished-at="2022-01-20T09:48:28 CST" duration-ms="493" status="PASS">
=======
        <test-method signature="badClaimIdForGetClaimService()[pri:0, instance:com.shield.tests.service.ClaimServiceTests@25bcd0c7]" started-at="2022-01-20T16:19:52 CST" name="badClaimIdForGetClaimService" finished-at="2022-01-20T16:19:52 CST" duration-ms="507" status="PASS">
>>>>>>> Stashed changes
          <exception class="com.shield.customexceptions.ClaimNotFound">
            <message>
              <![CDATA[Claim not found]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.shield.customexceptions.ClaimNotFound: Claim not found
at com.shield.daos.claim.ClaimDAOImp.getClaimById(ClaimDAOImp.java:54)
at com.shield.services.claim.ClaimServiceImp.getClaimByIdService(ClaimServiceImp.java:25)
at com.shield.tests.service.ClaimServiceTests.badClaimIdForGetClaimService(ClaimServiceTests.java:28)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.shield.customexceptions.ClaimNotFound -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- badClaimIdForGetClaimService -->
<<<<<<< Updated upstream
        <test-method signature="badEmployeeIdForCreateClaimService()[pri:0, instance:com.shield.tests.service.ClaimServiceTests@25bcd0c7]" started-at="2022-01-20T09:48:28 CST" name="badEmployeeIdForCreateClaimService" finished-at="2022-01-20T09:48:29 CST" duration-ms="475" status="PASS">
=======
        <test-method signature="badEmployeeIdForCreateClaimService()[pri:0, instance:com.shield.tests.service.ClaimServiceTests@25bcd0c7]" started-at="2022-01-20T16:19:52 CST" name="badEmployeeIdForCreateClaimService" finished-at="2022-01-20T16:19:53 CST" duration-ms="480" status="PASS">
>>>>>>> Stashed changes
          <exception class="com.shield.customexceptions.EmployeeNotFound">
            <message>
              <![CDATA[The employee was not found.]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.shield.customexceptions.EmployeeNotFound: The employee was not found.
at com.shield.daos.employee.EmployeeDAOImp.getEmployeeById(EmployeeDAOImp.java:69)
at com.shield.services.claim.ClaimServiceImp.createClaimService(ClaimServiceImp.java:31)
at com.shield.tests.service.ClaimServiceTests.badEmployeeIdForCreateClaimService(ClaimServiceTests.java:42)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.shield.customexceptions.EmployeeNotFound -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- badEmployeeIdForCreateClaimService -->
<<<<<<< Updated upstream
        <test-method signature="badUserIdForCreateClaimService()[pri:0, instance:com.shield.tests.service.ClaimServiceTests@25bcd0c7]" started-at="2022-01-20T09:48:29 CST" name="badUserIdForCreateClaimService" finished-at="2022-01-20T09:48:30 CST" duration-ms="965" status="PASS">
=======
        <test-method signature="badUserIdForCreateClaimService()[pri:0, instance:com.shield.tests.service.ClaimServiceTests@25bcd0c7]" started-at="2022-01-20T16:19:53 CST" name="badUserIdForCreateClaimService" finished-at="2022-01-20T16:19:54 CST" duration-ms="959" status="PASS">
>>>>>>> Stashed changes
          <exception class="com.shield.customexceptions.UserNotFound">
            <message>
              <![CDATA[User not found]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.shield.customexceptions.UserNotFound: User not found
at com.shield.daos.user.UserDAOImp.getUserById(UserDAOImp.java:51)
at com.shield.services.claim.ClaimServiceImp.createClaimService(ClaimServiceImp.java:32)
at com.shield.tests.service.ClaimServiceTests.badUserIdForCreateClaimService(ClaimServiceTests.java:35)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.shield.customexceptions.UserNotFound -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- badUserIdForCreateClaimService -->
<<<<<<< Updated upstream
        <test-method signature="commentTooLongForApproveClaimService()[pri:0, instance:com.shield.tests.service.ClaimServiceTests@25bcd0c7]" started-at="2022-01-20T09:48:30 CST" name="commentTooLongForApproveClaimService" finished-at="2022-01-20T09:48:30 CST" duration-ms="1" status="PASS">
=======
        <test-method signature="commentTooLongForApproveClaimService()[pri:0, instance:com.shield.tests.service.ClaimServiceTests@25bcd0c7]" started-at="2022-01-20T16:19:54 CST" name="commentTooLongForApproveClaimService" finished-at="2022-01-20T16:19:54 CST" duration-ms="0" status="PASS">
>>>>>>> Stashed changes
          <exception class="com.shield.customexceptions.CommentIsTooManyCharacters">
            <message>
              <![CDATA[Comment is too long]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.shield.customexceptions.CommentIsTooManyCharacters: Comment is too long
at com.shield.services.claim.ClaimServiceImp.approveClaimService(ClaimServiceImp.java:63)
at com.shield.tests.service.ClaimServiceTests.commentTooLongForApproveClaimService(ClaimServiceTests.java:62)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.shield.customexceptions.CommentIsTooManyCharacters -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- commentTooLongForApproveClaimService -->
<<<<<<< Updated upstream
        <test-method signature="commentTooLongForDenyClaimService()[pri:0, instance:com.shield.tests.service.ClaimServiceTests@25bcd0c7]" started-at="2022-01-20T09:48:30 CST" name="commentTooLongForDenyClaimService" finished-at="2022-01-20T09:48:30 CST" duration-ms="0" status="PASS">
=======
        <test-method signature="commentTooLongForDenyClaimService()[pri:0, instance:com.shield.tests.service.ClaimServiceTests@25bcd0c7]" started-at="2022-01-20T16:19:54 CST" name="commentTooLongForDenyClaimService" finished-at="2022-01-20T16:19:54 CST" duration-ms="0" status="PASS">
>>>>>>> Stashed changes
          <exception class="com.shield.customexceptions.CommentIsTooManyCharacters">
            <message>
              <![CDATA[Comment is too long]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.shield.customexceptions.CommentIsTooManyCharacters: Comment is too long
at com.shield.services.claim.ClaimServiceImp.approveClaimService(ClaimServiceImp.java:63)
at com.shield.tests.service.ClaimServiceTests.commentTooLongForDenyClaimService(ClaimServiceTests.java:69)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.shield.customexceptions.CommentIsTooManyCharacters -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- commentTooLongForDenyClaimService -->
<<<<<<< Updated upstream
        <test-method signature="negativeAmountForCreateClaimService()[pri:0, instance:com.shield.tests.service.ClaimServiceTests@25bcd0c7]" started-at="2022-01-20T09:48:30 CST" name="negativeAmountForCreateClaimService" finished-at="2022-01-20T09:48:31 CST" duration-ms="1100" status="PASS">
=======
        <test-method signature="negativeAmountForCreateClaimService()[pri:0, instance:com.shield.tests.service.ClaimServiceTests@25bcd0c7]" started-at="2022-01-20T16:19:54 CST" name="negativeAmountForCreateClaimService" finished-at="2022-01-20T16:19:55 CST" duration-ms="977" status="PASS">
>>>>>>> Stashed changes
          <exception class="com.shield.customexceptions.NegativeClaimAmount">
            <message>
              <![CDATA[Claim must be a positive number]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.shield.customexceptions.NegativeClaimAmount: Claim must be a positive number
at com.shield.services.claim.ClaimServiceImp.createClaimService(ClaimServiceImp.java:39)
at com.shield.tests.service.ClaimServiceTests.negativeAmountForCreateClaimService(ClaimServiceTests.java:48)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.shield.customexceptions.NegativeClaimAmount -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- negativeAmountForCreateClaimService -->
      </class> <!-- com.shield.tests.service.ClaimServiceTests -->
      <class name="com.shield.tests.service.DebriefServiceMockitoTest">
<<<<<<< Updated upstream
        <test-method is-config="true" signature="setup()[pri:0, instance:com.shield.tests.service.DebriefServiceMockitoTest@32cb636e]" started-at="2022-01-20T09:48:31 CST" name="setup" finished-at="2022-01-20T09:48:31 CST" duration-ms="9" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="createDebriefServiceMock()[pri:0, instance:com.shield.tests.service.DebriefServiceMockitoTest@32cb636e]" started-at="2022-01-20T09:48:31 CST" name="createDebriefServiceMock" finished-at="2022-01-20T09:48:31 CST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createDebriefServiceMock -->
        <test-method signature="mockGetDebriefServiceById()[pri:0, instance:com.shield.tests.service.DebriefServiceMockitoTest@32cb636e]" started-at="2022-01-20T09:48:31 CST" name="mockGetDebriefServiceById" finished-at="2022-01-20T09:48:31 CST" duration-ms="0" status="PASS">
=======
        <test-method is-config="true" signature="setup()[pri:0, instance:com.shield.tests.service.DebriefServiceMockitoTest@32cb636e]" started-at="2022-01-20T16:19:55 CST" name="setup" finished-at="2022-01-20T16:19:55 CST" duration-ms="7" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="createDebriefServiceMock()[pri:0, instance:com.shield.tests.service.DebriefServiceMockitoTest@32cb636e]" started-at="2022-01-20T16:19:55 CST" name="createDebriefServiceMock" finished-at="2022-01-20T16:19:55 CST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createDebriefServiceMock -->
        <test-method signature="mockGetDebriefServiceById()[pri:0, instance:com.shield.tests.service.DebriefServiceMockitoTest@32cb636e]" started-at="2022-01-20T16:19:55 CST" name="mockGetDebriefServiceById" finished-at="2022-01-20T16:19:55 CST" duration-ms="1" status="PASS">
>>>>>>> Stashed changes
          <reporter-output>
          </reporter-output>
        </test-method> <!-- mockGetDebriefServiceById -->
      </class> <!-- com.shield.tests.service.DebriefServiceMockitoTest -->
      <class name="com.shield.tests.service.EmployeeServiceTests">
<<<<<<< Updated upstream
        <test-method signature="badAgentGetAgentDebriefingsService()[pri:0, instance:com.shield.tests.service.EmployeeServiceTests@6fff253c]" started-at="2022-01-20T09:48:31 CST" name="badAgentGetAgentDebriefingsService" finished-at="2022-01-20T09:48:32 CST" duration-ms="498" status="PASS">
=======
        <test-method signature="badAgentGetAgentDebriefingsService()[pri:0, instance:com.shield.tests.service.EmployeeServiceTests@6fff253c]" started-at="2022-01-20T16:19:55 CST" name="badAgentGetAgentDebriefingsService" finished-at="2022-01-20T16:19:56 CST" duration-ms="492" status="PASS">
>>>>>>> Stashed changes
          <exception class="com.shield.customexceptions.EmployeeIsNotAgent">
            <message>
              <![CDATA[That employee is not an agent.]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.shield.customexceptions.EmployeeIsNotAgent: That employee is not an agent.
at com.shield.services.employee.EmployeeServiceImp.getAgentDebriefingsService(EmployeeServiceImp.java:83)
at com.shield.tests.service.EmployeeServiceTests.badAgentGetAgentDebriefingsService(EmployeeServiceTests.java:71)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.shield.customexceptions.EmployeeIsNotAgent -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- badAgentGetAgentDebriefingsService -->
<<<<<<< Updated upstream
        <test-method signature="badAgentGetUserClaimsByAgentService()[pri:0, instance:com.shield.tests.service.EmployeeServiceTests@6fff253c]" started-at="2022-01-20T09:48:32 CST" name="badAgentGetUserClaimsByAgentService" finished-at="2022-01-20T09:48:32 CST" duration-ms="506" status="PASS">
=======
        <test-method signature="badAgentGetUserClaimsByAgentService()[pri:0, instance:com.shield.tests.service.EmployeeServiceTests@6fff253c]" started-at="2022-01-20T16:19:56 CST" name="badAgentGetUserClaimsByAgentService" finished-at="2022-01-20T16:19:56 CST" duration-ms="491" status="PASS">
>>>>>>> Stashed changes
          <exception class="com.shield.customexceptions.EmployeeIsNotAgent">
            <message>
              <![CDATA[That employee is not an agent.]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.shield.customexceptions.EmployeeIsNotAgent: That employee is not an agent.
at com.shield.services.employee.EmployeeServiceImp.getUserClaimsByAgentService(EmployeeServiceImp.java:57)
at com.shield.tests.service.EmployeeServiceTests.badAgentGetUserClaimsByAgentService(EmployeeServiceTests.java:66)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.shield.customexceptions.EmployeeIsNotAgent -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- badAgentGetUserClaimsByAgentService -->
<<<<<<< Updated upstream
        <test-method signature="badHandlerForGetAllClaims()[pri:0, instance:com.shield.tests.service.EmployeeServiceTests@6fff253c]" started-at="2022-01-20T09:48:32 CST" name="badHandlerForGetAllClaims" finished-at="2022-01-20T09:48:33 CST" duration-ms="471" status="PASS">
=======
        <test-method signature="badHandlerForGetAllClaims()[pri:0, instance:com.shield.tests.service.EmployeeServiceTests@6fff253c]" started-at="2022-01-20T16:19:56 CST" name="badHandlerForGetAllClaims" finished-at="2022-01-20T16:19:57 CST" duration-ms="492" status="PASS">
>>>>>>> Stashed changes
          <exception class="com.shield.customexceptions.EmployeeIsNotHandler">
            <message>
              <![CDATA[That employee is not a handler.]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.shield.customexceptions.EmployeeIsNotHandler: That employee is not a handler.
at com.shield.services.employee.EmployeeServiceImp.getAllClaimsService(EmployeeServiceImp.java:42)
at com.shield.tests.service.EmployeeServiceTests.badHandlerForGetAllClaims(EmployeeServiceTests.java:54)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.shield.customexceptions.EmployeeIsNotHandler -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- badHandlerForGetAllClaims -->
<<<<<<< Updated upstream
        <test-method signature="badHandlerGetAllAgentDebriefingsService()[pri:0, instance:com.shield.tests.service.EmployeeServiceTests@6fff253c]" started-at="2022-01-20T09:48:33 CST" name="badHandlerGetAllAgentDebriefingsService" finished-at="2022-01-20T09:48:33 CST" duration-ms="476" status="PASS">
=======
        <test-method signature="badHandlerGetAllAgentDebriefingsService()[pri:0, instance:com.shield.tests.service.EmployeeServiceTests@6fff253c]" started-at="2022-01-20T16:19:57 CST" name="badHandlerGetAllAgentDebriefingsService" finished-at="2022-01-20T16:19:57 CST" duration-ms="486" status="PASS">
>>>>>>> Stashed changes
          <exception class="com.shield.customexceptions.EmployeeIsNotHandler">
            <message>
              <![CDATA[That employee is not a handler.]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.shield.customexceptions.EmployeeIsNotHandler: That employee is not a handler.
at com.shield.services.employee.EmployeeServiceImp.getAllAgentDebriefingsService(EmployeeServiceImp.java:70)
at com.shield.tests.service.EmployeeServiceTests.badHandlerGetAllAgentDebriefingsService(EmployeeServiceTests.java:59)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.shield.customexceptions.EmployeeIsNotHandler -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- badHandlerGetAllAgentDebriefingsService -->
<<<<<<< Updated upstream
        <test-method signature="badIdForGetAgentDebriefingsService()[pri:0, instance:com.shield.tests.service.EmployeeServiceTests@6fff253c]" started-at="2022-01-20T09:48:33 CST" name="badIdForGetAgentDebriefingsService" finished-at="2022-01-20T09:48:34 CST" duration-ms="480" status="PASS">
=======
        <test-method signature="badIdForGetAgentDebriefingsService()[pri:0, instance:com.shield.tests.service.EmployeeServiceTests@6fff253c]" started-at="2022-01-20T16:19:57 CST" name="badIdForGetAgentDebriefingsService" finished-at="2022-01-20T16:19:57 CST" duration-ms="476" status="PASS">
>>>>>>> Stashed changes
          <exception class="com.shield.customexceptions.EmployeeNotFound">
            <message>
              <![CDATA[The employee was not found.]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.shield.customexceptions.EmployeeNotFound: The employee was not found.
at com.shield.daos.employee.EmployeeDAOImp.getEmployeeById(EmployeeDAOImp.java:69)
at com.shield.services.employee.EmployeeServiceImp.getAgentDebriefingsService(EmployeeServiceImp.java:77)
at com.shield.tests.service.EmployeeServiceTests.badIdForGetAgentDebriefingsService(EmployeeServiceTests.java:38)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.shield.customexceptions.EmployeeNotFound -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- badIdForGetAgentDebriefingsService -->
<<<<<<< Updated upstream
        <test-method signature="badIdForGetAllAgentDebriefingsService()[pri:0, instance:com.shield.tests.service.EmployeeServiceTests@6fff253c]" started-at="2022-01-20T09:48:34 CST" name="badIdForGetAllAgentDebriefingsService" finished-at="2022-01-20T09:48:34 CST" duration-ms="489" status="PASS">
=======
        <test-method signature="badIdForGetAllAgentDebriefingsService()[pri:0, instance:com.shield.tests.service.EmployeeServiceTests@6fff253c]" started-at="2022-01-20T16:19:57 CST" name="badIdForGetAllAgentDebriefingsService" finished-at="2022-01-20T16:19:58 CST" duration-ms="473" status="PASS">
>>>>>>> Stashed changes
          <exception class="com.shield.customexceptions.EmployeeNotFound">
            <message>
              <![CDATA[The employee was not found.]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.shield.customexceptions.EmployeeNotFound: The employee was not found.
at com.shield.daos.employee.EmployeeDAOImp.getEmployeeById(EmployeeDAOImp.java:69)
at com.shield.services.employee.EmployeeServiceImp.getAllAgentDebriefingsService(EmployeeServiceImp.java:64)
at com.shield.tests.service.EmployeeServiceTests.badIdForGetAllAgentDebriefingsService(EmployeeServiceTests.java:33)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.shield.customexceptions.EmployeeNotFound -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- badIdForGetAllAgentDebriefingsService -->
<<<<<<< Updated upstream
        <test-method signature="badIdForGetAllClaims()[pri:0, instance:com.shield.tests.service.EmployeeServiceTests@6fff253c]" started-at="2022-01-20T09:48:34 CST" name="badIdForGetAllClaims" finished-at="2022-01-20T09:48:35 CST" duration-ms="471" status="PASS">
=======
        <test-method signature="badIdForGetAllClaims()[pri:0, instance:com.shield.tests.service.EmployeeServiceTests@6fff253c]" started-at="2022-01-20T16:19:58 CST" name="badIdForGetAllClaims" finished-at="2022-01-20T16:19:58 CST" duration-ms="504" status="PASS">
>>>>>>> Stashed changes
          <exception class="com.shield.customexceptions.EmployeeNotFound">
            <message>
              <![CDATA[The employee was not found.]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.shield.customexceptions.EmployeeNotFound: The employee was not found.
at com.shield.daos.employee.EmployeeDAOImp.getEmployeeById(EmployeeDAOImp.java:69)
at com.shield.services.employee.EmployeeServiceImp.getAllClaimsService(EmployeeServiceImp.java:36)
at com.shield.tests.service.EmployeeServiceTests.badIdForGetAllClaims(EmployeeServiceTests.java:23)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.shield.customexceptions.EmployeeNotFound -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- badIdForGetAllClaims -->
<<<<<<< Updated upstream
        <test-method signature="badIdForGetUserClaimsByAgentService()[pri:0, instance:com.shield.tests.service.EmployeeServiceTests@6fff253c]" started-at="2022-01-20T09:48:35 CST" name="badIdForGetUserClaimsByAgentService" finished-at="2022-01-20T09:48:35 CST" duration-ms="480" status="PASS">
=======
        <test-method signature="badIdForGetUserClaimsByAgentService()[pri:0, instance:com.shield.tests.service.EmployeeServiceTests@6fff253c]" started-at="2022-01-20T16:19:58 CST" name="badIdForGetUserClaimsByAgentService" finished-at="2022-01-20T16:19:59 CST" duration-ms="515" status="PASS">
>>>>>>> Stashed changes
          <exception class="com.shield.customexceptions.EmployeeNotFound">
            <message>
              <![CDATA[The employee was not found.]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.shield.customexceptions.EmployeeNotFound: The employee was not found.
at com.shield.daos.employee.EmployeeDAOImp.getEmployeeById(EmployeeDAOImp.java:69)
at com.shield.services.employee.EmployeeServiceImp.getUserClaimsByAgentService(EmployeeServiceImp.java:51)
at com.shield.tests.service.EmployeeServiceTests.badIdForGetUserClaimsByAgentService(EmployeeServiceTests.java:28)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.shield.customexceptions.EmployeeNotFound -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- badIdForGetUserClaimsByAgentService -->
<<<<<<< Updated upstream
        <test-method signature="badIdGetEmployeeImageService()[pri:0, instance:com.shield.tests.service.EmployeeServiceTests@6fff253c]" started-at="2022-01-20T09:48:35 CST" name="badIdGetEmployeeImageService" finished-at="2022-01-20T09:48:36 CST" duration-ms="486" status="PASS">
=======
        <test-method signature="badIdGetEmployeeImageService()[pri:0, instance:com.shield.tests.service.EmployeeServiceTests@6fff253c]" started-at="2022-01-20T16:19:59 CST" name="badIdGetEmployeeImageService" finished-at="2022-01-20T16:19:59 CST" duration-ms="485" status="PASS">
>>>>>>> Stashed changes
          <exception class="com.shield.customexceptions.EmployeeNotFound">
            <message>
              <![CDATA[The employee was not found.]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.shield.customexceptions.EmployeeNotFound: The employee was not found.
at com.shield.daos.employee.EmployeeDAOImp.getEmployeeById(EmployeeDAOImp.java:69)
at com.shield.services.employee.EmployeeServiceImp.getAgentDebriefingsService(EmployeeServiceImp.java:77)
at com.shield.tests.service.EmployeeServiceTests.badIdGetEmployeeImageService(EmployeeServiceTests.java:48)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.shield.customexceptions.EmployeeNotFound -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- badIdGetEmployeeImageService -->
<<<<<<< Updated upstream
        <test-method signature="badIdInsertEmployeeImageService()[pri:0, instance:com.shield.tests.service.EmployeeServiceTests@6fff253c]" started-at="2022-01-20T09:48:36 CST" name="badIdInsertEmployeeImageService" finished-at="2022-01-20T09:48:36 CST" duration-ms="494" status="PASS">
=======
        <test-method signature="badIdInsertEmployeeImageService()[pri:0, instance:com.shield.tests.service.EmployeeServiceTests@6fff253c]" started-at="2022-01-20T16:19:59 CST" name="badIdInsertEmployeeImageService" finished-at="2022-01-20T16:20:01 CST" duration-ms="1277" status="PASS">
>>>>>>> Stashed changes
          <exception class="com.shield.customexceptions.EmployeeNotFound">
            <message>
              <![CDATA[The employee was not found.]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.shield.customexceptions.EmployeeNotFound: The employee was not found.
at com.shield.daos.employee.EmployeeDAOImp.getEmployeeById(EmployeeDAOImp.java:69)
at com.shield.services.employee.EmployeeServiceImp.getAgentDebriefingsService(EmployeeServiceImp.java:77)
at com.shield.tests.service.EmployeeServiceTests.badIdInsertEmployeeImageService(EmployeeServiceTests.java:43)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.shield.customexceptions.EmployeeNotFound -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- badIdInsertEmployeeImageService -->
      </class> <!-- com.shield.tests.service.EmployeeServiceTests -->
      <class name="com.shield.tests.service.UserServiceMockitoTest">
<<<<<<< Updated upstream
        <test-method is-config="true" signature="setup()[pri:0, instance:com.shield.tests.service.UserServiceMockitoTest@6c6357f9]" started-at="2022-01-20T09:48:36 CST" name="setup" finished-at="2022-01-20T09:48:36 CST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="checkUsernameAndPasswordServiceMock()[pri:0, instance:com.shield.tests.service.UserServiceMockitoTest@6c6357f9]" started-at="2022-01-20T09:48:36 CST" name="checkUsernameAndPasswordServiceMock" finished-at="2022-01-20T09:48:36 CST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkUsernameAndPasswordServiceMock -->
        <test-method signature="checkUsernameAndPasswordServiceSadPasswordMock()[pri:0, instance:com.shield.tests.service.UserServiceMockitoTest@6c6357f9]" started-at="2022-01-20T09:48:36 CST" name="checkUsernameAndPasswordServiceSadPasswordMock" finished-at="2022-01-20T09:48:36 CST" duration-ms="0" status="PASS">
          <exception class="com.shield.customexceptions.InvalidPassword">
=======
        <test-method is-config="true" signature="setup()[pri:0, instance:com.shield.tests.service.UserServiceMockitoTest@6c6357f9]" started-at="2022-01-20T16:20:01 CST" name="setup" finished-at="2022-01-20T16:20:01 CST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="checkUsernameAndPasswordServiceMock()[pri:0, instance:com.shield.tests.service.UserServiceMockitoTest@6c6357f9]" started-at="2022-01-20T16:20:01 CST" name="checkUsernameAndPasswordServiceMock" finished-at="2022-01-20T16:20:01 CST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkUsernameAndPasswordServiceMock -->
        <test-method signature="checkUsernameAndPasswordServiceSadUsernameMock()[pri:0, instance:com.shield.tests.service.UserServiceMockitoTest@6c6357f9]" started-at="2022-01-20T16:20:01 CST" name="checkUsernameAndPasswordServiceSadUsernameMock" finished-at="2022-01-20T16:20:01 CST" duration-ms="1" status="PASS">
          <exception class="com.shield.customexceptions.InvalidUsername">
>>>>>>> Stashed changes
            <message>
              <![CDATA[Invalid password]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.shield.customexceptions.InvalidPassword: Invalid password
at com.shield.services.user.UserServicesImp.checkUserLoginService(UserServicesImp.java:76)
at com.shield.tests.service.UserServiceMockitoTest.checkUsernameAndPasswordServiceSadPasswordMock(UserServiceMockitoTest.java:114)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.shield.customexceptions.InvalidPassword -->
          <reporter-output>
          </reporter-output>
<<<<<<< Updated upstream
        </test-method> <!-- checkUsernameAndPasswordServiceSadPasswordMock -->
        <test-method signature="checkUsernameAndPasswordServiceSadUsernameMock()[pri:0, instance:com.shield.tests.service.UserServiceMockitoTest@6c6357f9]" started-at="2022-01-20T09:48:36 CST" name="checkUsernameAndPasswordServiceSadUsernameMock" finished-at="2022-01-20T09:48:36 CST" duration-ms="0" status="PASS">
          <exception class="com.shield.customexceptions.InvalidUsername">
=======
        </test-method> <!-- checkUsernameAndPasswordServiceSadUsernameMock -->
        <test-method signature="checkUsernameAndPasswordServiceSadPasswordMock()[pri:0, instance:com.shield.tests.service.UserServiceMockitoTest@6c6357f9]" started-at="2022-01-20T16:20:01 CST" name="checkUsernameAndPasswordServiceSadPasswordMock" finished-at="2022-01-20T16:20:01 CST" duration-ms="0" status="PASS">
          <exception class="com.shield.customexceptions.InvalidPassword">
>>>>>>> Stashed changes
            <message>
              <![CDATA[Invalid username]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.shield.customexceptions.InvalidUsername: Invalid username
at com.shield.services.user.UserServicesImp.checkUserLoginService(UserServicesImp.java:78)
at com.shield.tests.service.UserServiceMockitoTest.checkUsernameAndPasswordServiceSadUsernameMock(UserServiceMockitoTest.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.shield.customexceptions.InvalidUsername -->
          <reporter-output>
          </reporter-output>
<<<<<<< Updated upstream
        </test-method> <!-- checkUsernameAndPasswordServiceSadUsernameMock -->
        <test-method signature="createUserServiceMock()[pri:0, instance:com.shield.tests.service.UserServiceMockitoTest@6c6357f9]" started-at="2022-01-20T09:48:36 CST" name="createUserServiceMock" finished-at="2022-01-20T09:48:36 CST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createUserServiceMock -->
        <test-method signature="getAllClaimsByUserIdServiceMock()[pri:0, instance:com.shield.tests.service.UserServiceMockitoTest@6c6357f9]" started-at="2022-01-20T09:48:36 CST" name="getAllClaimsByUserIdServiceMock" finished-at="2022-01-20T09:48:36 CST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getAllClaimsByUserIdServiceMock -->
        <test-method signature="getAllUsersServiceMock()[pri:0, instance:com.shield.tests.service.UserServiceMockitoTest@6c6357f9]" started-at="2022-01-20T09:48:36 CST" name="getAllUsersServiceMock" finished-at="2022-01-20T09:48:36 CST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getAllUsersServiceMock -->
        <test-method signature="getUserServiceByIdMock()[pri:0, instance:com.shield.tests.service.UserServiceMockitoTest@6c6357f9]" started-at="2022-01-20T09:48:36 CST" name="getUserServiceByIdMock" finished-at="2022-01-20T09:48:36 CST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getUserServiceByIdMock -->
        <test-method signature="getUserServiceByIdSadMock()[pri:0, instance:com.shield.tests.service.UserServiceMockitoTest@6c6357f9]" started-at="2022-01-20T09:48:36 CST" name="getUserServiceByIdSadMock" finished-at="2022-01-20T09:48:36 CST" duration-ms="2" status="PASS">
=======
        </test-method> <!-- checkUsernameAndPasswordServiceSadPasswordMock -->
        <test-method signature="createUserServiceMock()[pri:0, instance:com.shield.tests.service.UserServiceMockitoTest@6c6357f9]" started-at="2022-01-20T16:20:01 CST" name="createUserServiceMock" finished-at="2022-01-20T16:20:01 CST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createUserServiceMock -->
        <test-method signature="getAllClaimsByUserIdServiceMock()[pri:0, instance:com.shield.tests.service.UserServiceMockitoTest@6c6357f9]" started-at="2022-01-20T16:20:01 CST" name="getAllClaimsByUserIdServiceMock" finished-at="2022-01-20T16:20:01 CST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getAllClaimsByUserIdServiceMock -->
        <test-method signature="getAllUsersServiceMock()[pri:0, instance:com.shield.tests.service.UserServiceMockitoTest@6c6357f9]" started-at="2022-01-20T16:20:01 CST" name="getAllUsersServiceMock" finished-at="2022-01-20T16:20:01 CST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getAllUsersServiceMock -->
        <test-method signature="getUserServiceByIdMock()[pri:0, instance:com.shield.tests.service.UserServiceMockitoTest@6c6357f9]" started-at="2022-01-20T16:20:01 CST" name="getUserServiceByIdMock" finished-at="2022-01-20T16:20:01 CST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getUserServiceByIdMock -->
        <test-method signature="getUserServiceByIdSadMock()[pri:0, instance:com.shield.tests.service.UserServiceMockitoTest@6c6357f9]" started-at="2022-01-20T16:20:01 CST" name="getUserServiceByIdSadMock" finished-at="2022-01-20T16:20:01 CST" duration-ms="1" status="PASS">
>>>>>>> Stashed changes
          <exception class="com.shield.customexceptions.UserNotFound">
            <message>
              <![CDATA[User not found]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.shield.customexceptions.UserNotFound: User not found
at com.shield.services.user.UserServicesImp.getUserByIdService(UserServicesImp.java:36)
at com.shield.tests.service.UserServiceMockitoTest.getUserServiceByIdSadMock(UserServiceMockitoTest.java:99)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.shield.customexceptions.UserNotFound -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getUserServiceByIdSadMock -->
      </class> <!-- com.shield.tests.service.UserServiceMockitoTest -->
    </test> <!-- Service -->
  </suite> <!-- Tests -->
</testng-results>
